line-length = 140
target-version = "py312"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "C4"]
ignore = ["E501", "B008", "UP007", "UP042", "UP046"]

[lint.per-file-ignores]
"tests/*" = ["E712", "F811", "B018"]
"alembic/*" = ["F401"]
