"""add requisicoes_estoque

Revision ID: 43b7d1e418d0
Revises: e07749e7c875
Create Date: 2026-09-07 09:50:55.243115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43b7d1e418d0'
down_revision: Union[str, None] = 'e07749e7c875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisicoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'COMPRADO', 'RECEBIDO', 'CANCELADO', name='statusrequisicao'), nullable=False),
    sa.Column('almoxarife_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compras_id', sa.Integer(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['almoxarife_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['compras_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisicoes_estoque_material_id'), 'requisicoes_estoque', ['material_id'], unique=False)
    op.create_index(op.f('ix_requisicoes_estoque_status'), 'requisicoes_estoque', ['status'], unique=False)
    op.create_index(op.f('ix_requisicoes_estoque_tenant'), 'requisicoes_estoque', ['tenant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisicoes_estoque_tenant'), table_name='requisicoes_estoque')
    op.drop_index(op.f('ix_requisicoes_estoque_status'), table_name='requisicoes_estoque')
    op.drop_index(op.f('ix_requisicoes_estoque_material_id'), table_name='requisicoes_estoque')
    op.drop_table('requisicoes_estoque')
    # ### end Alembic commands ###
