"""initial schema

Revision ID: e07749e7c875
Revises:
Create Date: 2026-09-04 02:51:42.549372
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "e07749e7c875"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("acao", sa.String(length=60), nullable=False),
        sa.Column("entidade", sa.String(length=60), nullable=False),
        sa.Column("entidade_id", sa.String(length=40), nullable=True),
        sa.Column("detalhe", sa.Text(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_acao"), "audit_log", ["acao"], unique=False)
    op.create_table(
        "classes_material",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classes_material_codigo"), "classes_material", ["codigo"], unique=False)
    op.create_index(op.f("ix_classes_material_tenant"), "classes_material", ["tenant"], unique=False)
    op.create_table(
        "colaboradores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.String(length=30), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("cargo", sa.String(length=80), nullable=True),
        sa.Column("centro_custo", sa.String(length=60), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_colaboradores_matricula"), "colaboradores", ["matricula"], unique=True)
    op.create_index(op.f("ix_colaboradores_tenant"), "colaboradores", ["tenant"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chave", sa.String(length=80), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=120), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("resposta", sa.Text(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_idempotency_keys_chave"), "idempotency_keys", ["chave"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=False),
        sa.Column("senha_hash", sa.String(length=200), nullable=False),
        sa.Column("papel", sa.Enum("ALMOXARIFE", "ADM_COMPRAS", "GERENTE", "DIRETOR", name="papel"), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("limite_alcada", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("mfa_secret", sa.String(length=64), nullable=True),
        sa.Column("mfa_ativo", sa.Boolean(), nullable=False),
        sa.Column("tentativas_login", sa.Integer(), nullable=False),
        sa.Column("bloqueado_ate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(op.f("ix_usuarios_papel"), "usuarios", ["papel"], unique=False)
    op.create_index(op.f("ix_usuarios_tenant"), "usuarios", ["tenant"], unique=False)
    op.create_table(
        "materiais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.Column("tipo", sa.Enum("CONSUMIVEL", "FERRAMENTA", "EPI", name="tipomaterial"), nullable=False),
        sa.Column("unidade", sa.String(length=10), nullable=False),
        sa.Column("classe_id", sa.Integer(), nullable=False),
        sa.Column("saldo_estoque", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("saldo_reservado", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("estoque_minimo", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("custo_medio", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("estoque_minimo >= 0", name="ck_minimo_nao_negativo"),
        sa.CheckConstraint("saldo_estoque >= 0", name="ck_saldo_nao_negativo"),
        sa.CheckConstraint("saldo_reservado >= 0", name="ck_reservado_nao_negativo"),
        sa.ForeignKeyConstraint(
            ["classe_id"],
            ["classes_material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_materiais_codigo"), "materiais", ["codigo"], unique=True)
    op.create_index(op.f("ix_materiais_tenant"), "materiais", ["tenant"], unique=False)
    op.create_index(op.f("ix_materiais_tipo"), "materiais", ["tipo"], unique=False)
    op.create_table(
        "pedidos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RASCUNHO",
                "AGUARDANDO_GERENTE",
                "AGUARDANDO_DIRETORIA",
                "APROVADO",
                "AGUARDANDO_COMPRA",
                "COMPRADO",
                "RECEBIDO",
                "REJEITADO",
                "CANCELADO",
                name="statuspedido",
            ),
            nullable=False,
        ),
        sa.Column("urgencia", sa.Enum("BAIXA", "MEDIA", "ALTA", "CRITICA", name="grauurgencia"), nullable=False),
        sa.Column("solicitante_id", sa.Integer(), nullable=False),
        sa.Column("aprovador_id", sa.Integer(), nullable=True),
        sa.Column("comprador_id", sa.Integer(), nullable=True),
        sa.Column("justificativa", sa.Text(), nullable=True),
        sa.Column("valor_estimado", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aprovador_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["comprador_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pedidos_numero"), "pedidos", ["numero"], unique=True)
    op.create_index(op.f("ix_pedidos_status"), "pedidos", ["status"], unique=False)
    op.create_index(op.f("ix_pedidos_tenant"), "pedidos", ["tenant"], unique=False)
    op.create_index(op.f("ix_pedidos_urgencia"), "pedidos", ["urgencia"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revogado", sa.Boolean(), nullable=False),
        sa.Column("substituido_por", sa.String(length=64), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_usuario_id"), "refresh_tokens", ["usuario_id"], unique=False)
    op.create_table(
        "comodatos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("colaborador_id", sa.Integer(), nullable=False),
        sa.Column("quantidade", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("status", sa.Enum("ABERTO", "DEVOLVIDO", "BAIXADO_PERDA", name="statuscomodato"), nullable=False),
        sa.Column("retirado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("devolvido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("almoxarife_id", sa.Integer(), nullable=False),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["almoxarife_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaboradores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiais.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comodatos_colaborador_id"), "comodatos", ["colaborador_id"], unique=False)
    op.create_index(op.f("ix_comodatos_material_id"), "comodatos", ["material_id"], unique=False)
    op.create_index(op.f("ix_comodatos_status"), "comodatos", ["status"], unique=False)
    op.create_index(op.f("ix_comodatos_tenant"), "comodatos", ["tenant"], unique=False)
    op.create_table(
        "historico_pedidos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("de_status", sa.String(length=30), nullable=True),
        sa.Column("para_status", sa.String(length=30), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("observacao", sa.Text(), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_historico_pedidos_pedido_id"), "historico_pedidos", ["pedido_id"], unique=False)
    op.create_table(
        "itens_pedido",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("qtd_solicitada", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("qtd_aprovada", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("qtd_comprada", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("custo_unitario", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.CheckConstraint("qtd_solicitada > 0", name="ck_item_qtd_positiva"),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiais.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_itens_pedido_pedido_id"), "itens_pedido", ["pedido_id"], unique=False)
    op.create_table(
        "movimentacoes_estoque",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.Enum("ENTRADA", "SAIDA", "DEVOLUCAO", "AJUSTE", name="tipomovimento"), nullable=False),
        sa.Column("quantidade", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("custo_unitario", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("saldo_apos", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("colaborador_id", sa.Integer(), nullable=True),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("observacao", sa.String(length=240), nullable=True),
        sa.Column("hash_anterior", sa.String(length=64), nullable=False),
        sa.Column("hash_atual", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant", sa.String(length=50), nullable=False),
        sa.CheckConstraint("quantidade > 0", name="ck_mov_qtd_positiva"),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaboradores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiais.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movimentacoes_estoque_material_id"), "movimentacoes_estoque", ["material_id"], unique=False)
    op.create_index(op.f("ix_movimentacoes_estoque_tenant"), "movimentacoes_estoque", ["tenant"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movimentacoes_estoque_tenant"), table_name="movimentacoes_estoque")
    op.drop_index(op.f("ix_movimentacoes_estoque_material_id"), table_name="movimentacoes_estoque")
    op.drop_table("movimentacoes_estoque")
    op.drop_index(op.f("ix_itens_pedido_pedido_id"), table_name="itens_pedido")
    op.drop_table("itens_pedido")
    op.drop_index(op.f("ix_historico_pedidos_pedido_id"), table_name="historico_pedidos")
    op.drop_table("historico_pedidos")
    op.drop_index(op.f("ix_comodatos_tenant"), table_name="comodatos")
    op.drop_index(op.f("ix_comodatos_status"), table_name="comodatos")
    op.drop_index(op.f("ix_comodatos_material_id"), table_name="comodatos")
    op.drop_index(op.f("ix_comodatos_colaborador_id"), table_name="comodatos")
    op.drop_table("comodatos")
    op.drop_index(op.f("ix_refresh_tokens_usuario_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_pedidos_urgencia"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_tenant"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_status"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_numero"), table_name="pedidos")
    op.drop_table("pedidos")
    op.drop_index(op.f("ix_materiais_tipo"), table_name="materiais")
    op.drop_index(op.f("ix_materiais_tenant"), table_name="materiais")
    op.drop_index(op.f("ix_materiais_codigo"), table_name="materiais")
    op.drop_table("materiais")
    op.drop_index(op.f("ix_usuarios_tenant"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_papel"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_idempotency_keys_chave"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_colaboradores_tenant"), table_name="colaboradores")
    op.drop_index(op.f("ix_colaboradores_matricula"), table_name="colaboradores")
    op.drop_table("colaboradores")
    op.drop_index(op.f("ix_classes_material_tenant"), table_name="classes_material")
    op.drop_index(op.f("ix_classes_material_codigo"), table_name="classes_material")
    op.drop_table("classes_material")
    op.drop_index(op.f("ix_audit_log_acao"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
